### ISSUE TITLE
Integrate into our Jenkins

### ISSUE THREAD

**Issue by Gregoor** [Common-Voice/common-voice-bundler#1]
Heya @gozer,

the README should contain everything that's needed to get it running. LMK if you also want me to send you the config to give this thing a test run.

Infra-wise the only strong need is >= 40GB storage and if possible storage that survives each run. Intention was that this way clips don't need to be re-downloaded on every run.  If it's super impractical I could also rewrite it to not depend on storage.

Thanks!

**Comment by The-smooth-operator** [comment]
I believe this issue is no longer relevant and can be closed
