### ISSUE TITLE
out/clips.tsv not found

### ISSUE THREAD

**Issue by bayethiernodiop** [Common-Voice/common-voice-bundler#3]
hello, i am trying to use the bundler in a local deployment but i have the error "out/clip.tsv No such file or directory". i looked at the code and i don't have this error when hashing is set to false. but i don't know if that hashing trick is useful for me and what it is used for. also where to get the out/clips.tsv file. thx in advance

**Comment by amansulaiman** [comment]
Hi @bayethiernodiop ,
Please how do you solve this issue? I am currently facing same

**Comment by DevloperHS** [comment]
Same problem unable to find clips.tsv file in zip
