### ISSUE TITLE
Common Voice 13 Dataset is missing `train`, `test`, `dev` splits

### ISSUE THREAD

**Issue by Vaibhavs10** [Common-Voice/common-voice-bundler#37]
Hi Common Voice team,

First of all, thank you for the brilliant effort and work you all put in to release such high-quality datasets.

We at Hugging Face, rely heavily on Common Voice datasets to build SoTA speech recognition models and open-source them for the community to build on.

We are in the process of incorporating the Common Voice 13 corpus on the Hugging Face Hub. We realised that the currently available data dumps on the https://commonvoice.mozilla.org/en/datasets do not contain the train, test and dev splits.

Is there any specific reason for only releasing the `invalidated`, `other`, `reported` and `validated` splits?

We're looking to run a community sprint soon to train open-source speech recognition models on CV13, hence need to have the dataset ready and in shape, for our participants to use efficiently.

Thank you again for all the support and work you do for the community!

**Comment by jessicarose** [comment]
Thanks so much for raising this, I'll bring this to the team now to try and get a better understanding of what's happened with these splits in the 13.0 release.

**Comment by Vaibhavs10** [comment]
Thanks for the prompt response @jessicarose.

I did some digging through the codebase and found a potential issue here: https://github.com/common-voice/common-voice-bundler/blob/6843bf0fbb3106e6092e2753eb1bb291fc048ec9/upload.js#L12

I think this change was introduced to support delta downloads with CV12: https://github.com/common-voice/common-voice-bundler/commit/aa92e18f8189ac23aacbf6b384826cbe0093b340

Looking forward to the fix!

**Comment by jessicarose** [comment]
Thanks again for flagging this, we'll be releasing splits shortly and having larger discussions about how to evolve these to better fit community and user needs in the future. We would love to have you all involved in these conversations as they start to develop. Thanks again!

**Comment by HarikalarKutusu** [comment]
@Vaibhavs10:

> We're looking to run a community sprint soon to train open-source speech recognition models on CV13, hence need to have the dataset ready and in shape, for our participants to use efficiently.

In the meantime, you can download the default and some alternative splits from the following link I provide, if it is OK for your workflow:
https://analyzer.cv-toolbox.web.tr/

**Comment by Vaibhavs10** [comment]
Hi @jessicarose - That's fantastic. Thanks for the update. Hugging Face is more than happy to be involved in supporting your efforts to democratize Common Voice further. I'll take the conversation further over emails.

Thanks & cheers!

**Comment by jessicarose** [comment]
Thanks again for raising this. These have been released and should be available for download on your side. Let me know if this isn't fixed as expected!
